Cluster-Ergebnisse:
Cluster D consists of 4 entries of 7 elements in total
Mean Pairwise-Sim before clustering = 0.875
Mean Pairwise-Sim after clustering = 0.25
Mean Sim-to-Rep before clustering = 1
Mean Sim-to-Rep after clustering = 0.25
Rep = D
[A, B, C, D]
Cluster F consists of 2 entries of 7 elements in total
Mean Pairwise-Sim before clustering = 1
Mean Pairwise-Sim after clustering = 0.375
Mean Sim-to-Rep before clustering = 1
Mean Sim-to-Rep after clustering = 0.5
Rep = F
[E, F]
Cluster G consists of 2 entries of 7 elements in total
Mean Pairwise-Sim before clustering = 1
Mean Pairwise-Sim after clustering = 0.375
Mean Sim-to-Rep before clustering = 1
Mean Sim-to-Rep after clustering = 0.5
Rep = G
[E, G]
